version: '3.7'

services:
  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080

  # server:
  #   container_name: web-server
  #   restart: unless-stopped
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   volumes:
  #     - ./src:/usr/app/src
  #   ports:
  #     - 5000:5000


#docker-compose up -d
#docker ps
